# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "gaskin-terraform-state"
    dynamodb_table = "terraform-lock-table"
    encrypt        = true
    key            = "./terraform.tfstate"
    profile        = "terraform"
    region         = "us-east-1"
    role_arn       = "arn:aws:iam::211125642696:role/terraform"
  }
}
